apiVersion: v1
kind: Service
metadata: 
  name: cluster-insight
  namespace: default
  labels: 
    k8s-app: cluster-insight
    kubernetes.io/name: ClusterInsight
    version: v1
spec: 
  selector: 
    cluster-insight-mode: master
  ports: 
    - 
      name: cluster-insight
      port: 5555
      targetPort: cluster-insight
      protocol: TCP
